---

- name: minibufexpl
  urls:
    - http://www.vim.org/scripts/script.php?script_id=159
  description: 'Elegant buffer explorer - takes very little screen space'
  repo_type: git
  #Use the maintained branch
  repo: git://github.com/fholgado/minibufexpl.vim.git
  plugin_type: plugin
  file_type: vim

- name: IndexedSearch
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1682
  description: "shows  'Nth match out of M'  at every search (index of match+total # matches)"
  repo_type: git
  repo: git://github.com/vim-scripts/IndexedSearch.git
  plugin_type: plugin
  file_type: vim

- name: NERDCommenter
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1218
  repo_type: git
  repo: git://github.com/scrooloose/nerdcommenter.git
  description: 'A plugin that allows for easy commenting of code for many filetypes'
  plugin_type: plugin

- name: NERDtree
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1658
  repo_type: git
  repo: git://github.com/scrooloose/nerdtree.git
  description: 'A tree explorer plugin for navigating the filesystem'
  plugin_type: plugin

- name: ack
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2572
  repo_type: git
  repo: git://github.com/mileszs/ack.vim.git
  description: "Plugin for the Perl module / CLI script 'ack'"
  plugin_type: plugin
  file_type: tar.gz

- name: mark
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1238
  description: 'a little script to highlight several words in different colors simultaneously'
  repo_type: git
  repo: git://github.com/vim-scripts/Mark.git
  plugin_type: plugin
  #vim_org_id: 8603
  file_type: vim

- name: replace_with_register
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2703
  repo_type: git
  repo: git://github.com/vim-scripts/ReplaceWithRegister.git
  description: "Replace text with content of register"
  plugin_type: plugin

- name: unite
  repo_type: git
  repo: git://github.com/Shougo/unite.vim.git
  description: 'Unite and create user interfaces'
  plugin_type: plugin

- name: neocomplete
  repo_type: git
  repo: git://github.com/Shougo/neocomplete.vim.git
  description: 'A new autocomplete solution'
  plugin_type: plugin

#- name: vimfiler
  #repo_type: git
  #repo: git://github.com/Shougo/vimfiler.vim.git
  #description: 'Powerful file explorer implemented by Vim script'
  #plugin_type: plugin

- name: vim-git
  urls:
    - http://github.com/tpope/vim-git
    - http://www.vim.org/scripts/script.php?script_id=1654
  repo_type: git
  repo: git://github.com/tpope/vim-git.git
  description: 'Git runtime files'
  plugin_type: plugin

# This plugin depends on vim-git
- name: fugitive
  urls:
    - http://github.com/tpope/vim-fugitive
    - http://www.vim.org/scripts/script.php?script_id=2975
  repo_type: git
  repo: git://github.com/tpope/vim-fugitive.git
  description: 'Git wrapper'
  plugin_type: plugin

# Used in lookupfile -- utilities for scripts
#- name: genutils
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=197
  #description: 'General utility functions'
  #repo_type: git
  #repo: git://github.com/vim-scripts/genutils.git
  #plugin_type: plugin
  ##vim_org_id: 11399
  #file_type: zip

#- name: lookupfile
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=1581
  #description: 'Lookup files using Vim7 ins-completion'
  #repo_type: git
  #repo: git://github.com/vim-scripts/lookupfile.git
  #plugin_type: plugin
  ##vim_org_id: 7671
  #file_type: zip

- name: matchit
  urls:
    - http://www.vim.org/scripts/script.php?script_id=39
  description: 'extended % matching for HTML, LaTeX, and many other languages'
  repo_type: git
  repo: git://github.com/vim-scripts/matchit.zip.git
  plugin_type: plugin
  #vim_org_id: 8196
  file_type: zip

- name: MarksBrowser
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1706
  description: "This script provides a graphical browsers of the user marks for the local file [a-z]"
  repo_type: git
  repo: git://github.com/vim-scripts/Marks-Browser.git
  plugin_type: plugin
  #vim_org_id: 6408 # 0.9, 2006-11-13, 7.0
  file_type: vim

#- name: taglist
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=273
#  description: 'Source code browser (supports C/C++, java, perl, python, tcl, sql, etc)'
#  repo_type: git
#  repo: git://github.com/vim-scripts/taglist.vim.git
#  plugin_type: plugin
#  #vim_org_id: 7701 # 4.5, 2007-09-21, 6.0
#  file_type: zip

- name: tagbar
  urls:
    - http://www.vim.org/scripts/script.php?script_id=3465
  repo: git://github.com/majutsushi/tagbar.git
  repo_type: git
  description: 'Display tags of the current file ordered by scope'
  plugin_type: plugin

#- name: jQuery
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=2416
#  description: 'some colorations for jQuery keywords and for CSS selectors'
#  repo_type: git
#  repo: git://github.com/vim-scripts/jQuery.git
#  plugin_type: syntax
#  #vim_org_id: 12107 # 0.4, 2010-02-02, 6.0
#  file_type: vim

- name: yankstack
  description: A lightweight implementation of emacs's kill-ring for vim
  repo_type: git
  repo: git://github.com/maxbrunsfeld/vim-yankstack.git
  plugin_type: plugin 

- name: osx_like
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2170
  description: 'Color scheme that uses MacOS X like colors'
  repo_type: git
  repo: git://github.com/vim-scripts/osx_like.git
  plugin_type: colors
  #vim_org_id: 8362
  file_type: vim

#This doesn't seem to actually work this way without modification.  Had to create hack_repo as a hack.
- name: pyflakes
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2441
  repo: git://github.com/kevinw/pyflakes-vim.git
  repo_type: git
  description: 'PyFlakes on-the-fly Python code checking'
  plugin_type: ftplugin
  dir: pyflakes
  hack_repo: git://github.com/kevinw/pyflakes.git
  hack_dir: ftplugin/python/pyflakes

#- name: fakeclip
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=2098
#  repo_type: git
#  repo: git://github.com/kana/vim-fakeclip.git
#  description: 'Make copy/paste work with the system clipboard.'
#  plugin_type: plugin
#  file_type: zip

- name: keepcase
  urls:
    - http://www.vim.org/scripts/script.php?script_id=6
  description: 'Functions for doing case-persistant substitutions'
  repo_type: git
  repo: git://github.com/vim-scripts/keepcase.vim.git
  plugin_type: plugin
  #vim_org_id: 6942
  file_type: vim

- name: syntastic
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2736
  repo_type: git
  repo: git://github.com/scrooloose/syntastic.git
  description: 'Automatic syntax checking'
  plugin_type: plugin
  file_type: vim

- name: spacebars
  repo_type: git
  repo: https://github.com/Slava/vim-spacebars.git
  description: 'Syntax highlighting and indenting for spacebars.'
  plugin_type: plugin
  file_type: vim

- name: handlebars
  repo_type: git
  repo: https://github.com/nono/vim-handlebars.git
  description: 'Syntax highlighting and indenting for mustache/handlebars.'
  plugin_type: plugin
  file_type: vim

- name: vim-less
  repo_type: git
  repo: git://github.com/groenewege/vim-less.git
  description: 'Syntax highlighting for .less stylesheets.'
  plugin_type: plugin
  file_type: vim

- name: vim-markdown
  repo_type: git
  repo: git://github.com/tpope/vim-markdown.git
  description: 'Vim Markdown runtime files.'
  plugin_type: plugin
  file_type: vim

#- name: checksyntax
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=1431
  #repo_type: git
  #repo: git://github.com/tomtom/checksyntax_vim.git
  #description: 'Checks syntax in a variety of languages.'
  #plugin_type: plugin
  #file_type: vim

- name: alternate
  urls:
    - http://www.vim.org/scripts/script.php?script_id=31
  description: 'Alternate header/implementation quickly'
  repo_type: git
  repo: git://github.com/vim-scripts/a.vim.git
  plugin_type: plugin
  #vim_org_id: 7218
  file_type: vim

#- name: TaskList
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=2607
  #description: 'TaskList from TODO and FIXME statements in code.'
  #repo_type: git
  #repo: git://github.com/vim-scripts/TaskList.vim.git
  #plugin_type: plugin
  ##vim_org_id: 10388
  #file_type: vim

- name: camelcasemotion
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1905
  description: 'Motion through CamelCaseWords and underscore_notation'
  repo_type: git
  repo: git://github.com/vim-scripts/camelcasemotion.git
  plugin_type: plugin
  file_type: vim

- name: toggle_words
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1676
  description: "toggle words like:'true'=>'false', 'True'=>'False' etc"
  repo_type: git
  repo: git://github.com/vim-scripts/toggle_words.vim.git
  plugin_type: plugin
  file_type: vim

#- name: rails
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=1567
  #description: 'Ruby on Rails: easy file navigation, enhanced syntax highlighting, and more'
  #repo_type: git
  #repo: git://github.com/tpope/vim-rails.git
  #plugin_type: plugin
  #file_type: vim

#- name: Cocoa
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=2674
  #repo_type: git
  #repo: git://github.com/msanders/cocoa.vim.git
  #description: 'Plugin for Cocoa/Objective-C development'
  #plugin_type: plugin

- name: coffeeScript
  repo_type: git
  repo: git://github.com/kchmck/vim-coffee-script.git
  description: 'CoffeeScript support for vim'
  plugin_type: plugin

- name: html5
  repo_type: git
  repo: git@github.com:othree/html5.vim.git
  description: 'HTML5 highlighting'
  plugin_type: plugin

#Might be causing infinite loop?
#- name: tern_for_vim
  #repo_type: git
  #repo: https://github.com/marijnh/tern_for_vim.git
  #description: "Tern Javascript support for vim."
  #plugin_type: plugin
  #extra: npm

- name: json
  description: A syntax highlighting file for JSON
  repo_type: git
  repo: git://github.com/vim-scripts/JSON.vim.git
  plugin_type: plugin

- name: closetag
  urls:
    - http://www.vim.org/scripts/script.php?script_id=13
  description: 'Functions and mappings to close open HTML/XML tags'
  repo_type: git
  repo: git://github.com/vim-scripts/closetag.vim.git
  plugin_type: plugin
  file_type: vim

- name: nodejs-complete
  description: Nodejs 'omnifunc' function of vim
  repo: git://github.com/myhere/vim-nodejs-complete.git
  repo_type: git
  plugin_type: plugin
  file_type: vim

- name: javascript-syntax
  description: 'JavaScript bundle for vim, this bundle provides syntax and indent plugins.'
  repo: git://github.com/pangloss/vim-javascript.git
  repo_type: git
  plugin_type: plugin
  file_type: vim

- name: match-tag
  description: 'Highlight matching HTML tag.'
  repo: git://github.com/gregsexton/MatchTag.git
  repo_type: git
  plugin_type: plugin
  file_type: vim

- name: indent-guides
  description: A Vim plugin for visually displaying indent levels in code
  repo: git://github.com/nathanaelkane/vim-indent-guides.git
  repo_type: git
  plugin_type: plugin
  file_type: vim

- name: puppet
  description: Puppet niceties for your Vim setup
  repo: git://github.com/rodjek/vim-puppet.git
  repo_type: git
  plugin_type: plugin
  file_type: vim

#- name: netrw
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=1075
#  description: 'Read and write files remotely'
#  repo_type: git
#  repo: git://github.com/vim-scripts/netrw.vim.git
#  plugin_type: plugin
#  file_type: vim

#- name: clipbrd
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=1014
  #description: 'Clipboard and other register content editor.'
  #repo_type: git
  #repo: git://github.com/vim-scripts/clipbrd.git
  #plugin_type: plugin
  ##vim_org_id: 7201
  #file_type: vim

- name: surround
  description: 'Delete/change/add parentheses/quotes/XML-tags/much more with ease'
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1697
  repo: git://github.com/tpope/vim-surround.git
  repo_type: git
  plugin_type: plugin

- name: ragtag
  description: 'A set of mappings for HTML, XML, PHP, ASP, eRuby, JSP, and more (formerly allml)'
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1896
  repo: git://github.com/tpope/vim-ragtag.git
  repo_type: git
  plugin_type: plugin

#- name: delimitMate
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=2754
#  repo: git://github.com/Raimondi/delimitMate.git
#  description: 'Provides auto-balancing and some expansions for parens, quotes, etc.'
#  plugin_type: plugin

#- name: snipMate
#  urls:
#    - http://www.vim.org/scripts/script.php?script_id=2540
#  repo: git://github.com/msanders/snipmate.vim.git
#  repo_type: git
#  description: 'TextMate-style snippets for Vim'
#  plugin_type: plugin

#- name: FuzzyFinder
  #urls:
    #- http://www.vim.org/scripts/script.php?script_id=1984
  ##repo: https://bitbucket.org/ns9tks/vim-fuzzyfinder
  #description: 'buffer/file/command/tag/etc explorer with fuzzy matching'
  #plugin_type: plugin
  #vim_org_id: 13961 # 3.5, 2009-12-03, 7.0
  #file_type: zip


